package codigo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juana
 */
public class pnl_err extends javax.swing.JPanel {

    /**
     * Creates new form pnl_err
     */
    public pnl_err() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsjError = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(null);

        lblMsjError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMsjError.setForeground(new java.awt.Color(255, 255, 255));
        lblMsjError.setText("Mensaje de error");
        add(lblMsjError);
        lblMsjError.setBounds(30, 20, 1280, 22);

        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        add(btnInfo);
        btnInfo.setBounds(1140, 20, 53, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        System.out.println(this.getName().toString());
    }//GEN-LAST:event_btnInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnInfo;
    public static javax.swing.JLabel lblMsjError;
    // End of variables declaration//GEN-END:variables
}
