package codigo;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author juana
 */
public class pnlSalida extends javax.swing.JPanel {

    /**
     * Creates new form pnlSalida
     */
    JButton boton1 = new JButton();
    DefaultTableModel modelo = new DefaultTableModel();

    public boolean isCellEditable(int row, int column) {
        return false;
    }
    
    public pnlSalida() {
        initComponents();
        mostrar();

    }

    public void mostrar() {
        /*TablaErrores.getTableHeader().setUI(null);
        //TablaErrores.setDefaultRenderer(Object.class, new RenderTabla());
        //modelo = new DefaultTableModel(
                new Object[][]{{"Errores Sintácticos", "Ventana de Errores"}},
                new Object[]{"Error", ""}
        //);
        //TablaErrores.setModel(modelo);*/
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollSalida = new javax.swing.JScrollPane();
        pnlErroresList = new javax.swing.JPanel();

        setBackground(new java.awt.Color(101, 101, 117));
        setPreferredSize(new java.awt.Dimension(1420, 325));
        setLayout(null);

        scrollSalida.setPreferredSize(new java.awt.Dimension(1400, 330));

        pnlErroresList.setBackground(new java.awt.Color(101, 101, 117));
        pnlErroresList.setPreferredSize(new java.awt.Dimension(1400, 325));
        pnlErroresList.setLayout(null);
        scrollSalida.setViewportView(pnlErroresList);

        add(scrollSalida);
        scrollSalida.setBounds(0, 0, 1400, 325);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel pnlErroresList;
    public static javax.swing.JScrollPane scrollSalida;
    // End of variables declaration//GEN-END:variables
}
