package codigo;


import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditEvent;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultCaret;
import static javax.swing.text.DefaultCaret.ALWAYS_UPDATE;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juana
 */
public class Compiler_Run extends javax.swing.JFrame {

    /**
     * Creates new form Compiler_Run
     */
    public Compiler_Run() {
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception e){
            e.printStackTrace();
        }
        initComponents();
        try{
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Graphics/logo.png")).getImage());}
        catch(Exception exp){   
        }
        
      Document doc = codeArea.getDocument();
      doc.addDocumentListener(new DocumentListener() {
      @Override
      public void changedUpdate(DocumentEvent e) {
        lineNumbers();
      }

      @Override
      public void insertUpdate(DocumentEvent e) {
        lineNumbers();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        lineNumbers();
      }
      
    });

    codeArea.requestFocus();
    ini();
    addTabs();
    scrollNumeroLine.setWheelScrollingEnabled(false);
    scrollNumeroLine.addMouseWheelListener(new MouseWheelListener() {
        public void mouseWheelMoved(MouseWheelEvent e) {
            scrollCodeArea.dispatchEvent(e);
        }
    });
    }
    
    
     private void lineNumbers() {
    try {
      String str = codeArea.getText();

      // Plain Style
      SimpleAttributeSet plain = new SimpleAttributeSet();

      // Bold style
      SimpleAttributeSet bold = new SimpleAttributeSet();
      StyleConstants.setBold(bold, true);

      // Remove all from document
      Document doc = numeroLine.getDocument();
      doc.remove(0, doc.getLength());

      // Calculating the number of lines
      int length = str.length() - str.replaceAll("\n", "").length() + 1;

      // Adding line-numbers
      for (int i = 1; i <= length; i++) {

        // Non-bold line-numbers
        if (i < length) {
          doc.insertString(doc.getLength(), i + "\n", plain);

        // Last line-number bold
        } else {
          doc.insertString(doc.getLength(), i + "\n", bold);
        }
      }
    } catch (BadLocationException e) {
      e.printStackTrace();
    }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Area = new javax.swing.JPanel();
        scrollCodeArea = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextPane();
        scrollNumeroLine = new javax.swing.JScrollPane();
        numeroLine = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblLines = new javax.swing.JLabel();
        jtabComp = new javax.swing.JTabbedPane();
        lexico = new javax.swing.JLabel();
        udo = new javax.swing.JLabel();
        newFile = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        saveas = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        redo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        exec = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        config = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/logo.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 48));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 43)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 232, 165));
        jLabel1.setText("Hiver");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/minimize.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(48, 48));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1766, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/close.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(48, 48));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1824, 30, -1, -1));

        Area.setBackground(new java.awt.Color(78, 78, 92));

        scrollCodeArea.setBorder(null);
        scrollCodeArea.setPreferredSize(new java.awt.Dimension(1, 22));

        codeArea.setBackground(new java.awt.Color(78, 78, 92));
        codeArea.setBorder(null);
        codeArea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        codeArea.setForeground(new java.awt.Color(255, 255, 255));
        codeArea.setCaretColor(new java.awt.Color(255, 255, 255));
        codeArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        codeArea.setPreferredSize(new java.awt.Dimension(100, 22));
        codeArea.setSelectedTextColor(new java.awt.Color(0, 204, 102));
        codeArea.setSelectionColor(new java.awt.Color(255, 255, 255));
        codeArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeAreaKeyReleased(evt);
            }
        });
        scrollCodeArea.setViewportView(codeArea);

        scrollNumeroLine.setBorder(null);
        scrollNumeroLine.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollNumeroLine.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        numeroLine.setEditable(false);
        numeroLine.setBackground(new java.awt.Color(101, 101, 117));
        numeroLine.setBorder(null);
        numeroLine.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        numeroLine.setForeground(new java.awt.Color(153, 255, 204));
        numeroLine.setFocusable(false);
        scrollNumeroLine.setViewportView(numeroLine);

        jPanel2.setBackground(new java.awt.Color(101, 101, 117));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lineas:");

        lblLines.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        lblLines.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLines, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1683, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtabComp.setBackground(new java.awt.Color(51, 51, 61));
        jtabComp.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout AreaLayout = new javax.swing.GroupLayout(Area);
        Area.setLayout(AreaLayout);
        AreaLayout.setHorizontalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaLayout.createSequentialGroup()
                .addGroup(AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AreaLayout.createSequentialGroup()
                        .addComponent(scrollNumeroLine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(scrollCodeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaLayout.createSequentialGroup()
                .addComponent(jtabComp)
                .addContainerGap())
        );
        AreaLayout.setVerticalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaLayout.createSequentialGroup()
                .addGroup(AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollNumeroLine, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(scrollCodeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtabComp, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 103, -1, -1));

        lexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/sintac.png"))); // NOI18N
        lexico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 38, -1, -1));

        udo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/back.png"))); // NOI18N
        udo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        udo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                udoMouseClicked(evt);
            }
        });
        jPanel1.add(udo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 38, -1, -1));

        newFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/new.png"))); // NOI18N
        newFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newFileMouseClicked(evt);
            }
        });
        jPanel1.add(newFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/guardar.png"))); // NOI18N
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 38, -1, -1));

        saveas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/saveas.png"))); // NOI18N
        saveas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveasMouseClicked(evt);
            }
        });
        jPanel1.add(saveas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 38, -1, -1));

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/openFile.png"))); // NOI18N
        open.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMouseClicked(evt);
            }
        });
        jPanel1.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 38, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Abrir");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 73, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Guardar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 73, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nuevo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 73, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar como");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 73, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Deshacer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 73, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rehacer");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 73, -1, -1));

        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/redo.png"))); // NOI18N
        redo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redoMouseClicked(evt);
            }
        });
        jPanel1.add(redo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 42, -1, 24));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("An. Léxico");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 73, -1, -1));

        exec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/compile.png"))); // NOI18N
        exec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                execMouseClicked(evt);
            }
        });
        jPanel1.add(exec, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 38, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Compilar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 73, -1, -1));

        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/config.png"))); // NOI18N
        config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 38, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ajustes");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 73, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try{
            if(!name.getAbsolutePath().equals("")){
            int confir=JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);   
            if(confir== JOptionPane.YES_OPTION){guardar();System.exit(0);}
            else System.exit(0);
            }else System.exit(0);
        }catch(java.lang.NullPointerException ex){ System.exit(0);}
    }//GEN-LAST:event_jLabel3MouseClicked

    private void execMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_execMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_execMouseClicked

    private void addTabs(){
        pnlSalida p1 = new pnlSalida();
        pnlTablaFija ptf = new pnlTablaFija();
        pnlTablaDinamica ptd = new pnlTablaDinamica();
        jtabComp.add("Salida",p1);
        jtabComp.add("Tablas fijas",ptf);
        jtabComp.add("Tablas dinámicas",ptd);
        
    }
    
        private void ini(){
        undoKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_Z, KeyEvent.CTRL_DOWN_MASK);
        redoKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_Y, KeyEvent.CTRL_DOWN_MASK);
        undoManager = new UndoManager();
        Document document = codeArea.getDocument();
        document.addUndoableEditListener((UndoableEditEvent e) -> {
            undoManager.addEdit(e.getEdit());
        });
        
        codeArea.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
            .put(undoKeyStroke, "undoKeyStroke");
        codeArea.getActionMap().put("undoKeyStroke", new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            try {
                undoManager.undo();
             } catch (CannotUndoException cue) {}
        }
    });
        
        codeArea.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
            .put(redoKeyStroke, "redoKeyStroke");
        codeArea.getActionMap().put("redoKeyStroke", new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            try {
                undoManager.redo();
             } catch (CannotRedoException cre) {}
        }
        });
    }
    
    private int cuentaLin(){
         String A[]=codeArea.getText().split("\n");
         int p=0;
         for(int i=0;i<A.length;i++)if(!A[i].equals("\n"))p++;
         return p;
    }
        
    private void openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMouseClicked
        try {
            JFileChooser chooser=new JFileChooser();
            chooser.showOpenDialog(this);//Terminar el editor de texto
            name=new File(chooser.getSelectedFile().toString());
            doc = codeArea.getStyledDocument();
            editorKit = new RTFEditorKit();
            java.io.FileInputStream fbr=new java.io.FileInputStream(name);
           try {
               codeArea.setText("");
               editorKit.read(fbr, doc, 0);
               lblLines.setText(cuentaLin()+" lineas");
           } catch (BadLocationException ex) {
               Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
        } catch(java.lang.NullPointerException ex){  
        }
    }//GEN-LAST:event_openMouseClicked

       private void guardar(){
        try{
            if(!name.getName().equals("")){
            fbw = new FileOutputStream(name,false);
            doc = codeArea.getStyledDocument();
            editorKit = new RTFEditorKit();
            try {
                try {
                    editorKit.write(fbw, doc, 0, doc.getLength());
                } catch (IOException ex) {
                    Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
        }catch(NullPointerException err){  
            showMessageDialog(this,name.getName());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void saveasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveasMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(this);
            name=new File(chooser.getSelectedFile()+".hiv");
            
            if(name.getName().matches("^[a-zA-Z0-9\\sñÑ]+[.][h][i][v]$")){
                fbw = new FileOutputStream(name,false);
                doc = codeArea.getStyledDocument();
                editorKit = new RTFEditorKit();
                try {
                    editorKit.write(fbw, doc, 0, doc.getLength());
                } catch (BadLocationException ex) {
                    Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{ 
                if(name.getName().matches("^[a-zñA-ZÑ0-9\\s]+[.][h][i][v][.][h][i][v]$")){
                    int confir=JOptionPane.showConfirmDialog(null, "¿Quieres remplazarlo?", "Archivo Existente", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);   
                    if(confir== JOptionPane.YES_OPTION){
                        fbw = new FileOutputStream(name,false);
                        doc = codeArea.getStyledDocument();
                        editorKit = new RTFEditorKit();
                        try {
                            editorKit.write(fbw, doc, 0, doc.getLength());
                        } catch (BadLocationException ex) {
                            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else{
                    showMessageDialog(null,"Nombre o dirección mal ingresada");
                    saveas.requestFocus();
                }
            }
        }catch (FileNotFoundException ex) {
            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Compiler_Run.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException err){   
        }
    }//GEN-LAST:event_saveasMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        guardar();
    }//GEN-LAST:event_saveMouseClicked

    private void redoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redoMouseClicked
        try {
            undoManager.redo();
        } catch (CannotRedoException cre) {}
    }//GEN-LAST:event_redoMouseClicked

    private void udoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udoMouseClicked
        try {
            undoManager.undo();
        } catch (CannotUndoException cue) {}
    }//GEN-LAST:event_udoMouseClicked

    private void codeAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeAreaKeyReleased
        lblLines.setText(cuentaLin()+" lineas");
    }//GEN-LAST:event_codeAreaKeyReleased

    private void newFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newFileMouseClicked
        this.dispose();
    }//GEN-LAST:event_newFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compiler_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compiler_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compiler_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compiler_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compiler_Run().setVisible(true);
            }
        });
    }
    private String fuentes[];
    private FileOutputStream fbw;
    private Font fuent;
    private int size=12;
    private File name;
    private int start;
    private int end;
    private StyledDocument doc;
    private Element element;
    private AttributeSet as;
    private MutableAttributeSet asNew;
    private SimpleAttributeSet align;
    private KeyStroke undoKeyStroke;
    private KeyStroke redoKeyStroke;
    private UndoManager undoManager;
    private RTFEditorKit editorKit;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Area;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextPane codeArea;
    private javax.swing.JLabel config;
    private javax.swing.JLabel exec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jtabComp;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lexico;
    private javax.swing.JLabel newFile;
    private javax.swing.JTextPane numeroLine;
    private javax.swing.JLabel open;
    private javax.swing.JLabel redo;
    private javax.swing.JLabel save;
    private javax.swing.JLabel saveas;
    private javax.swing.JScrollPane scrollCodeArea;
    private javax.swing.JScrollPane scrollNumeroLine;
    private javax.swing.JLabel udo;
    // End of variables declaration//GEN-END:variables
}
