package codigo;


import java.awt.Color;
import java.awt.Dimension;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juana
 */
public class pnlTablaDinamica extends javax.swing.JPanel {

    /**
     * Creates new form pnlTablaFija
     */
    public pnlTablaDinamica() {
        initComponents();
        tblDinSim.setShowGrid(false);
        tblDinSim.setIntercellSpacing(new Dimension(0,0));
        tblDinSim.setOpaque(false);
        ((DefaultTableCellRenderer)tblDinSim.getDefaultRenderer(Object.class)).setOpaque(false);
        scrollDinSim.setOpaque(false);
        scrollDinSim.getViewport().setOpaque(false);
        JTableHeader header = tblDinSim.getTableHeader();
        header.setOpaque(false);
        header.setBackground(new Color(51,51,61));
        header.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        scrollDinSim = new javax.swing.JScrollPane();
        tblDinSim = new javax.swing.JTable();

        setBackground(new java.awt.Color(101, 101, 117));
        setPreferredSize(new java.awt.Dimension(1390, 438));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tabla de variables");

        tblDinSim.setBackground(new java.awt.Color(101, 101, 117));
        tblDinSim.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        tblDinSim.setForeground(new java.awt.Color(255, 255, 255));
        tblDinSim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Valor", "Ubicación", "Ámbito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollDinSim.setViewportView(tblDinSim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDinSim, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollDinSim, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollDinSim;
    public javax.swing.JTable tblDinSim;
    // End of variables declaration//GEN-END:variables
}
