package codigo;


import java.awt.Color;
import java.awt.Dimension;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juana
 */
public class pnlTablaFija extends javax.swing.JPanel {

    /**
     * Creates new form pnlTablaFija
     */
    public pnlTablaFija() {
        initComponents();
        tblPalRes.setShowGrid(false);
        tblPalRes.setIntercellSpacing(new Dimension(0,0));
        tblPalRes.setOpaque(false);
        ((DefaultTableCellRenderer)tblPalRes.getDefaultRenderer(Object.class)).setOpaque(false);
        scrollPalRes.setOpaque(false);
        scrollPalRes.getViewport().setOpaque(false);
        JTableHeader header = tblPalRes.getTableHeader();
        header.setOpaque(false);
        header.setBackground(new Color(51,51,61));
        header.setForeground(Color.WHITE);
        tblErr.setIntercellSpacing(new Dimension(0,0));
        tblErr.setOpaque(false);
        ((DefaultTableCellRenderer)tblErr.getDefaultRenderer(Object.class)).setOpaque(false);
        scrollErr.setOpaque(false);
        scrollErr.getViewport().setOpaque(false);
        JTableHeader header2 = tblErr.getTableHeader();
        header2.setOpaque(false);
        header2.setBackground(new Color(51,51,61));
        header2.setForeground(Color.WHITE);
        
         tblErr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Número incorrecto"},
                {"2", "El identificador no es válido"},
                {"3", "Símbolo Invalido"}
            },
            new String [] {
                "ID Error", "Tipo de error"
            }
        ));
        tblPalRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"if", "res_if"},
            {"else", "res_else"},
            {"while", "res_while"},
            {"do", "res_do"},
            {"for", "res_for"},
            {"exit", "res_exit"},
            {"return", "res_return"},
            {"function", "res_function"},
            {"void", "res_void"},
            {"null", "res_null"},
            {"input", "res_input"},
            {"output", "res_output"},
            {"in", "res_in"},
            {"out", "res_out"},
            {"def", "res_def"},
            {"true", "res_true"},
            {"false", "res_false"},
            {"start", "res_start"},
            {"end", "res_end"},
            {"array", "res_array"},
            {"type", "res_type"},
            {"display", "res_display"},
            {"config", "res_config"},
            {"scale", "res_scale"},
            {"pin", "res_pin"},
            {"volt", "res_volt"},
            {"wait", "res_wait"},
            {"mode", "res_mode"},
            {"sleep", "res_sleep"},
            {"switch", "res_switch"},
            {"default", "res_dafault"},
            {"name", "res_name"},
            {"max_volt", "res_max_volt"},
            {"-", "ari_resta"},
            {"+", "ari_suma"},
            {"*", "ari_multiplicacion"},
            {"/", "ari_divicion"},
            {"and", "log_and"},
            {"or", "log_or"},
            {"xor", "log_xor"},
            {"not", "log_not"},
            {">", "rel_mayor"},
            {"<", "rel_menor"},
            {">=", "rel_mayor_igual"},
            {"<=", "rel_menor_igual"},
            {"==", "rel_igual"},
            {"!=", "rel_diferente"},
            {"=", "asi_asignacion"},
            {";", "sig_punto_coma"},
            {"(", "par_abre"},
            {")", "par_cierra"},
            {"{", "llave_abre"},
            {"}", "llave_cierra"},
            {"[", "cor_abre"},
            {"]", "cor_cierra"},
            {"tinyint", "tip_tinyint"},
            {"int", "tip_int"},
            {"float", "tip_float"},
            {"double", "tip_double"},
            {"char", "tip_char"},
            {".", "sim_punto"},
            {":", "sim_dos_puntos"}
            },
            new String [] {
                "Lexema", "Comp. Léxico"
            }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollErr = new javax.swing.JScrollPane();
        tblErr = new javax.swing.JTable();
        scrollPalRes = new javax.swing.JScrollPane();
        tblPalRes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(101, 101, 117));
        setMinimumSize(new java.awt.Dimension(1390, 325));
        setPreferredSize(new java.awt.Dimension(1390, 325));

        tblErr.setBackground(new java.awt.Color(101, 101, 117));
        tblErr.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        tblErr.setForeground(new java.awt.Color(255, 255, 255));
        tblErr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Error", "Tipo de error"
            }
        ));
        scrollErr.setViewportView(tblErr);

        tblPalRes.setBackground(new java.awt.Color(101, 101, 117));
        tblPalRes.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        tblPalRes.setForeground(new java.awt.Color(255, 255, 255));
        tblPalRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lexema", "Comp. Léxico"
            }
        ));
        scrollPalRes.setViewportView(tblPalRes);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla fija de errores");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tabla fija de palabras reservadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPalRes, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollErr, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollErr, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(scrollPalRes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollErr;
    private javax.swing.JScrollPane scrollPalRes;
    private javax.swing.JTable tblErr;
    private javax.swing.JTable tblPalRes;
    // End of variables declaration//GEN-END:variables
}
