
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 10 19:24:18 MDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rel_mayor_igual = 48;
  public static final int log_or = 42;
  public static final int Identificador_no_valido = 70;
  public static final int res_default = 33;
  public static final int res_pin = 27;
  public static final int rel_igual = 24;
  public static final int res_start = 19;
  public static final int res_out = 15;
  public static final int res_def = 16;
  public static final int res_in = 14;
  public static final int res_model = 30;
  public static final int llave_abre = 53;
  public static final int res_true = 17;
  public static final int sig_punto_coma = 50;
  public static final int rel_menor = 45;
  public static final int res_if = 2;
  public static final int res_max_volt = 35;
  public static final int sim_dos_puntos = 57;
  public static final int par_abre = 51;
  public static final int tip_int = 59;
  public static final int res_void = 10;
  public static final int res_else = 3;
  public static final int ERROR = 76;
  public static final int Error_numerico = 73;
  public static final int res_null = 11;
  public static final int tip_boolean = 63;
  public static final int cor_cierra = 56;
  public static final int res_switch = 32;
  public static final int ari_multiplicacion = 39;
  public static final int res_return = 8;
  public static final int res_for = 6;
  public static final int Error_simbolo_no_valido = 72;
  public static final int asi_asignacion = 36;
  public static final int Numero_incorrecto4 = 75;
  public static final int Numero_incorrecto3 = 74;
  public static final int Numero_incorrecto2 = 69;
  public static final int cadena_caracter = 67;
  public static final int res_exit = 7;
  public static final int Numero_incorrecto1 = 68;
  public static final int tip_double = 61;
  public static final int ari_suma = 37;
  public static final int tip_tinyint = 58;
  public static final int res_output = 13;
  public static final int Error_simbo_punto = 71;
  public static final int par_cierra = 52;
  public static final int res_false = 18;
  public static final int EOF = 0;
  public static final int log_and = 41;
  public static final int res_array = 21;
  public static final int res_wait = 29;
  public static final int res_display = 23;
  public static final int res_end = 20;
  public static final int Numero = 65;
  public static final int log_xor = 43;
  public static final int res_volt = 28;
  public static final int res_scale = 26;
  public static final int cor_abre = 55;
  public static final int error = 1;
  public static final int rel_mayor = 46;
  public static final int res_type = 22;
  public static final int res_while = 4;
  public static final int res_function = 9;
  public static final int Identificador = 64;
  public static final int res_name = 34;
  public static final int ari_division = 40;
  public static final int res_input = 12;
  public static final int tip_char = 62;
  public static final int coma = 66;
  public static final int res_sleep = 31;
  public static final int rel_diferente = 49;
  public static final int tip_float = 60;
  public static final int rel_menor_igual = 47;
  public static final int res_config = 25;
  public static final int res_do = 5;
  public static final int llave_cierra = 54;
  public static final int ari_resta = 38;
  public static final int log_not = 44;
}

