package codigo;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dalia
 */
public enum Tokens {
   res_if,
   res_else,
   res_while,
 res_do,
 res_for,
res_exit,
 res_return,
  res_function,
  res_void,
 res_null,
  res_input,
 res_output,
  res_in,
 res_out,
 res_def,
 res_true,
 res_false,
 res_start,
 res_end,
 res_array,
 res_type,
res_display,rel_igual,
 res_config,
 res_scale,
 res_pin,
 res_volt,
res_wait,
res_model,
res_sleep,
res_switch,
 res_default,
res_name, res_max_volt,
asi_asignacion,
ari_suma,
ari_resta,
ari_multiplicacion,
ari_division,
log_and,
log_or,
log_xor,
log_not,
rel_menor,
rel_mayor,
rel_menor_igual,
 rel_mayor_igual,
rel_diferente,
 sig_punto_coma,
par_abre,
par_cierra,
llave_abre,
llave_cierra,
cor_abre,
cor_cierra,
sim_dos_puntos,
tip_tinyint,
tip_int,
tip_float,
 tip_double,
tip_char,
Identificador,
tip_boolean,
Numero,coma,cadena_caracter,
Numero_incorrecto1,Numero_incorrecto2,
Identificador_no_valido,
Error_simbo_punto,
Error_simbolo_no_valido,
Error_numerico,
Numero_incorrecto3,
Numero_incorrecto4,
ERROR
}
